site_name: Mouette


theme:
  name: material

  features:
    - navigation.instant
    - navigation.sections
    - navigation.indexes
    - toc.follow

plugins:
- search
- autorefs
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths: [mouette/]
        options:
          show_root_toc_entry: false
          show_root_heading: false
          show_signature_annotations: false
          show_signature: true
          show_source: false
          merge_init_into_class: true
          docstring_style: "google"
          docstring_section_style: table
          inherited_members: true
- mkdocs-nav-weight:
    section_renamed: false
    index_weight: -10
    warning: true
    reverse: false
    headless_included: false


markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - toc:
      toc_depth: 3
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

repo_url: https://github.com/GCoiffier/mouette
repo_name: GCoiffier/mouette