site_name: Mouette

theme:
  name: material

  features:
    - navigation.sections
    - navigation.indexes

plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths: [mouette/]
        options:
          show_root_toc_entry: false
          show_root_heading: false
          show_signature_annotations: false
          show_signature: true
          show_source: false
          docstring_style: "google"

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

repo_url: https://github.com/GCoiffier/mouette
repo_name: GCoiffier/mouette